import sqlite3
from dataclasses import dataclass
from pathlib import Path

import psycopg
from psycopg import sql


TABLES = (
    "estados",
    "ceasas",
    "entrepostos",
    "categorias",
    "produtos",
    "produto_aliases",
    "unidades",
    "apresentacoes_unidade",
    "coletas",
    "cotacoes",
)

POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS estados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    uf TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ceasas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado_id BIGINT NOT NULL REFERENCES estados (id),
    slug TEXT NOT NULL UNIQUE,
    nome TEXT NOT NULL,
    url_origem TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS entrepostos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ceasa_id BIGINT NOT NULL REFERENCES ceasas (id),
    slug TEXT NOT NULL,
    nome TEXT NOT NULL,
    UNIQUE (ceasa_id, slug)
);

CREATE TABLE IF NOT EXISTS categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_normalizado TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS produto_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL REFERENCES produtos (id),
    nome_original TEXT NOT NULL,
    UNIQUE (produto_id, nome_original)
);

CREATE TABLE IF NOT EXISTS unidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sigla TEXT NOT NULL UNIQUE,
    descricao TEXT
);

CREATE TABLE IF NOT EXISTS apresentacoes_unidade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chave_unica TEXT NOT NULL UNIQUE,
    unidade_id BIGINT REFERENCES unidades (id),
    unidade_original TEXT,
    unidade_normalizada TEXT,
    embalagem TEXT,
    quantidade_minima NUMERIC,
    quantidade_maxima NUMERIC,
    detalhe_unidade TEXT
);

CREATE TABLE IF NOT EXISTS coletas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chave_unica TEXT NOT NULL UNIQUE,
    ceasa_id BIGINT NOT NULL REFERENCES ceasas (id),
    arquivo_raw TEXT,
    hash_raw TEXT,
    url_origem TEXT NOT NULL,
    baixado_em TIMESTAMP,
    processado_em TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS cotacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chave_unica TEXT NOT NULL UNIQUE,
    chave_identidade TEXT NOT NULL,
    coleta_id BIGINT NOT NULL REFERENCES coletas (id),
    entreposto_id BIGINT REFERENCES entrepostos (id),
    categoria_id BIGINT NOT NULL REFERENCES categorias (id),
    produto_alias_id BIGINT NOT NULL REFERENCES produto_aliases (id),
    apresentacao_unidade_id BIGINT REFERENCES apresentacoes_unidade (id),
    data_cotacao DATE NOT NULL,
    preco_minimo NUMERIC CHECK (preco_minimo IS NULL OR preco_minimo >= 0),
    preco_comum NUMERIC CHECK (preco_comum IS NULL OR preco_comum >= 0),
    preco_maximo NUMERIC CHECK (preco_maximo IS NULL OR preco_maximo >= 0),
    procedencia TEXT,
    classificacao TEXT,
    situacao_mercado TEXT,
    fonte_complemento TEXT,
    url_complemento TEXT,
    data_complemento TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_coletas_ceasa ON coletas (ceasa_id);
CREATE INDEX IF NOT EXISTS idx_cotacoes_identidade ON cotacoes (chave_identidade);
CREATE INDEX IF NOT EXISTS idx_cotacoes_coleta ON cotacoes (coleta_id);
CREATE INDEX IF NOT EXISTS idx_cotacoes_entreposto_data
    ON cotacoes (entreposto_id, data_cotacao);
CREATE INDEX IF NOT EXISTS idx_cotacoes_categoria_data
    ON cotacoes (categoria_id, data_cotacao);
CREATE INDEX IF NOT EXISTS idx_cotacoes_produto_data
    ON cotacoes (produto_alias_id, data_cotacao);
CREATE INDEX IF NOT EXISTS idx_produto_aliases_produto
    ON produto_aliases (produto_id);

ALTER TABLE estados ENABLE ROW LEVEL SECURITY;
ALTER TABLE ceasas ENABLE ROW LEVEL SECURITY;
ALTER TABLE entrepostos ENABLE ROW LEVEL SECURITY;
ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE produto_aliases ENABLE ROW LEVEL SECURITY;
ALTER TABLE unidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE apresentacoes_unidade ENABLE ROW LEVEL SECURITY;
ALTER TABLE coletas ENABLE ROW LEVEL SECURITY;
ALTER TABLE cotacoes ENABLE ROW LEVEL SECURITY;
"""


@dataclass(frozen=True)
class SupabaseSyncResult:
    table_counts: dict[str, int]

    @property
    def total_count(self) -> int:
        return sum(self.table_counts.values())


@dataclass(frozen=True)
class SupabaseSynchronizer:
    sqlite_path: Path
    database_url: str
    batch_size: int = 5_000

    def sync(self) -> SupabaseSyncResult:
        if not self.sqlite_path.exists():
            raise FileNotFoundError(f"Banco SQLite nao encontrado em {self.sqlite_path}.")

        table_counts: dict[str, int] = {}

        with sqlite3.connect(self.sqlite_path) as source:
            source.row_factory = sqlite3.Row

            with psycopg.connect(self.database_url) as target:
                target.execute("SET search_path TO public")
                target.execute(POSTGRES_SCHEMA)

                for table_name in TABLES:
                    table_counts[table_name] = self._sync_table(
                        source,
                        target,
                        table_name,
                    )

        return SupabaseSyncResult(table_counts)

    def _sync_table(
        self,
        source: sqlite3.Connection,
        target: psycopg.Connection,
        table_name: str,
    ) -> int:
        columns = self._get_columns(source, table_name)
        temporary_table = f"sync_{table_name}"
        target.execute(
            sql.SQL("CREATE TEMP TABLE {} (LIKE {} INCLUDING DEFAULTS) ON COMMIT DROP").format(
                sql.Identifier(temporary_table),
                sql.Identifier(table_name),
            )
        )

        source_cursor = source.execute(
            sql.SQL("SELECT {} FROM {} ORDER BY id").format(
                sql.SQL(", ").join(map(sql.Identifier, columns)),
                sql.Identifier(table_name),
            ).as_string()
        )
        copied_count = 0
        copy_query = sql.SQL("COPY {} ({}) FROM STDIN").format(
            sql.Identifier(temporary_table),
            sql.SQL(", ").join(map(sql.Identifier, columns)),
        )

        with target.cursor().copy(copy_query) as copy:
            while rows := source_cursor.fetchmany(self.batch_size):
                for row in rows:
                    copy.write_row(tuple(row))
                copied_count += len(rows)

        update_columns = [column for column in columns if column != "id"]
        target.execute(
            sql.SQL(
                "INSERT INTO {} ({columns}) SELECT {columns} FROM {} "
                "ON CONFLICT (id) DO UPDATE SET {updates}"
            ).format(
                sql.Identifier(table_name),
                sql.Identifier(temporary_table),
                columns=sql.SQL(", ").join(map(sql.Identifier, columns)),
                updates=sql.SQL(", ").join(
                    sql.SQL("{} = EXCLUDED.{}").format(
                        sql.Identifier(column),
                        sql.Identifier(column),
                    )
                    for column in update_columns
                ),
            )
        )
        target.execute(
            "SELECT setval(pg_get_serial_sequence(%s, 'id'), "
            "COALESCE((SELECT MAX(id) FROM " + table_name + "), 1), true)",
            (table_name,),
        )
        return copied_count

    def _get_columns(
        self,
        source: sqlite3.Connection,
        table_name: str,
    ) -> list[str]:
        return [
            str(row["name"])
            for row in source.execute(f"PRAGMA table_info({table_name})")
        ]
